### ISSUE TITLE
能否上架微软商店

### ISSUE THREAD

**Issue by ChirmyRam** [Paving-Base/APK-Installer#1]
上架后更新会方便很多。

**Comment by phoenixlucky** [comment]
微软的审核比较慢，感觉。

**Comment by Meng5in** [comment]
> > > 话说买开发人员账号可以不用visa卡吗。。。
> > 
> > 
> > 开发人员账号我不清楚，不知道能不能用虚拟visa卡？我搞到过🤔
> 
> 很好奇其他开发者是怎么搞的，Visa卡并不是所有人都有啊。。。

Visa借记卡可以吗？借记卡不需要什么资质。

**Comment by Meng5in** [comment]
能上架Microsoft store的话就真的太好了。

**Comment by oxygen-dioxide** [comment]
另一款wsa apk安装器，wsatools，被下架了
https://www.ithome.com/0/585/756.htm

**Comment by Meng5in** [comment]
[手动滑稽]

**Comment by Meng5in** [comment]
> 另一款wsa apk安装器，wsatools，被下架了 https://www.ithome.com/0/585/756.htm

这个昨天刚更新完今天就被下架了🤣🤣🥀

**Comment by oxygen-dioxide** [comment]
不过没被Github封杀，还是存在一点希望的

**Comment by Meng5in** [comment]
> 上架后更新会方便很多。

能做成.exe或者.msi的话，加进winget也挺方便的。

**Comment by Meng5in** [comment]
> 上架后更新会方便很多。

能做成.exe或者.msi的话，加进winget也挺方便的。

**Comment by wherewhere** [comment]
> 能上架Microsoft store的话就真的太好了。

现在看来是不能上架了，不过隔壁那个纯WPF的我是打算上架<img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />

**Comment by weathon** [comment]
前几天还看到那个wsatool还在现在听说下架了，但是现在似乎恢复了？https://www.neowin.net/news/microsoft-apologized-and-restores-wsatools-but-it-was-rightful-in-removing-it/

**Comment by wherewhere** [comment]
> 前几天还看到那个wsatool还在现在听说下架了，但是现在似乎恢复了？https://www.neowin.net/news/microsoft-apologized-and-restores-wsatools-but-it-was-rightful-in-removing-it/

到时候上架WinGet就是了，反正我已经成功上架了一个(WinGet管的不严

**Comment by wherewhere** [comment]
我已经买了开发者账号了，但是现在上架有一堆问题，估计得折腾一个月。。。
(我先上架一个小软件试试水<img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />

**Comment by Meng5in** [comment]
冲🎉

**Comment by wherewhere** [comment]
正在审核<img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />
![Screenshot_20211210-123500.jpg](https://user-images.githubusercontent.com/27689196/145518039-047444dd-08ea-4970-be66-30bd3ffb6040.jpg)

**Comment by Meng5in** [comment]
> 正在审核<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"><img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"><img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"> ![Screenshot_20211210-123500.jpg](https://user-images.githubusercontent.com/27689196/145518039-047444dd-08ea-4970-be66-30bd3ffb6040.jpg)

**Comment by Meng5in** [comment]
> 正在审核<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"><img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"><img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"> ![Screenshot_20211210-123500.jpg](https://user-images.githubusercontent.com/27689196/145518039-047444dd-08ea-4970-be66-30bd3ffb6040.jpg)

现在上架了吗？

**Comment by wherewhere** [comment]
> > 正在审核<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"><img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"><img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png"> ![Screenshot_20211210-123500.jpg](https://user-images.githubusercontent.com/27689196/145518039-047444dd-08ea-4970-be66-30bd3ffb6040.jpg)
> 
> 现在上架了吗？
> 

NOP，微软不理我。。。
(如果下周一之前再没反应的话估计是凉凉了。。。

**Comment by wherewhere** [comment]
讨厌，上架失败。。。
![Screenshot_20211213-235946.jpg](https://user-images.githubusercontent.com/27689196/145845887-abe79045-afeb-45b3-ad7c-89863d541714.jpg)

**Comment by Meng5in** [comment]
为啥不给过啊？

**Comment by wherewhere** [comment]
上架成功
https://www.microsoft.com/store/apps/9P2JFQ43FPPG

**Comment by ChirmyRam** [comment]
> 上架成功 https://www.microsoft.com/store/apps/9P2JFQ43FPPG

nice!

**Comment by Meng5in** [comment]
终于成功了，楼主稳！！！

> 上架成功 https://www.microsoft.com/store/apps/9P2JFQ43FPPG
