### ISSUE TITLE
Missing translation for an error screen.

### ISSUE THREAD

**Issue by NomadicVoxel** [Paving-Base/APK-Installer#102]
This happens the first time I tried to install an APK file. I'm thinking I didn't have WSA running, but I don't have a clue if this error is related to that, as I can't read this language. (Is this Japanese? Chinese? sorry.) 
![image](https://user-images.githubusercontent.com/36419454/155893695-14efc015-1ddd-4e1e-9fb7-2a5233fc0f93.png)

**Comment by NomadicVoxel** [comment]
Someone on Reddit translated it for me, for anyone else coming in. 
"Title: How to connect to Android subsystem
    Please make sure the APK Installer has been updated to the newest version (hyperlink)
    Please make sure you have installed and ran the Android subsystem
    Turn on Developer Mode, make sure the IP address is displayed
    Reopen APK Installer, resume installation"
https://www.reddit.com/r/translator/comments/t2tlhl/unknown_japanese_english_im_using_windows_11s/

**Comment by wherewhere** [comment]
#80

**Comment by wherewhere** [comment]
This test is store here https://github.com/Paving-Base/APK-Installer/blob/screenshots/Documents/Tutorials/How To Connect WSA/How To Connect WSA.md . You can try to make a commit.

**Comment by wherewhere** [comment]
Updated #108
