### ISSUE TITLE
installation failed cause the certificare even if i installed before run install.ps1

### ISSUE THREAD

**Issue by MaiSan9999** [Paving-Base/APK-Installer#129]
so after install the certificate and run the uwp it doesn't work i mean it say it's not trusted even if i installed the certificate.
when i run the install.ps1 

This app package is not signed with a trusted certificate. Contact your system administrator or app developer to get a new certificate or app package with trusted certificates. The root certificate and all immediate signing certificates in the app package must be trusted (0x800B010A)
![image](https://user-images.githubusercontent.com/89659009/157741862-c7f7691e-8106-4ad3-b5db-fd9538efca77.png)

**Comment by wherewhere** [comment]
It’s Coolapk, not APK Installer...
