### ISSUE TITLE
希望能够在软件起始页面和apk选取完成等待安装界面添加设置入口

### ISSUE THREAD

**Issue by dadawdsda** [Paving-Base/APK-Installer#156]
### Describe your feature request

希望能够在软件起始页面和apk选取完成等待安装界面添加设置入口
在WSA运行时选取apk后没有能进入设置界面的入口，无法给手机安装应用
：D

### How important is this to you?

Nice-to-have

### Describe the solution you'd like

在软件起始页面和选取apk后等待安装界面增加设置入口

**Comment by wherewhere** [comment]
实际上设置入口就在左上角，你随时可以进去。。。

**Comment by dadawdsda** [comment]
![image](https://user-images.githubusercontent.com/78917739/161430070-b663a27d-6d5a-4c6f-b32d-a0c47bc95f44.png)
没看着啊大佬
![WD$XN4L~WJZC)IAL {`V5VN](https://user-images.githubusercontent.com/78917739/161430086-24f5fd46-c686-4f45-aef6-d63c11ee16c1.png)

**Comment by wherewhere** [comment]
> ![image](https://user-images.githubusercontent.com/78917739/161430070-b663a27d-6d5a-4c6f-b32d-a0c47bc95f44.png)
> 没看着啊大佬
> ![WD$XN4L~WJZC)IAL {`V5VN](https://user-images.githubusercontent.com/78917739/161430086-24f5fd46-c686-4f45-aef6-d63c11ee16c1.png)
> 

用Tab(WinUI的Bug

**Comment by dadawdsda** [comment]
![image](https://user-images.githubusercontent.com/78917739/161431906-a12dca6e-e754-4e3f-9b6a-d475778377eb.png)
wow！
感谢大佬回复
