### ISSUE TITLE
微软商店的0.1.13版本打开闪退

### ISSUE THREAD

**Issue by Qing-JiuJiu** [Paving-Base/APK-Installer#169]
### Describe the bug

因重装系统在微软商店下载该程序，但打开APK时，根据任务管理器的显示，程序运行几秒后自动关闭，未有任何弹窗显示，GitHub上的0.1.12暂无该问题。

### Steps to reproduce the bug

双击APK文件打开

### Expected behavior

弹出安装APK的窗口

### App version

0.1.12

### Windows version

Windows 11 version 21H2 (22000)

### Android device

Windows Subsystem for Android™

**Comment by MC5Spear** [comment]
我刚刚使用0.1.13版本也闪退了，在控制管理器里可以看到一闪而过的windows错误报告。
![屏幕截图 2022-04-22 112035](https://user-images.githubusercontent.com/104182356/164589954-e1235466-727b-4b5e-ab8c-c6e1785dd148.png)

**Comment by wherewhere** [comment]
可能是WAS出现严重Bug，即将回退

**Comment by wherewhere** [comment]
已经找到问题的原因了，运行库没有安装，WAS真是问题一大堆啊。。。

**Comment by Qing-JiuJiu** [comment]
> 已经找到问题的原因了，库没有运行安装，真是一大堆问题啊。。。

好的，谢谢回复，请尽快修复。

**Comment by wherewhere** [comment]
> > 已经找到问题的原因了，库没有运行安装，真是一大堆问题啊。。。
> 
> 好的，谢谢回复，请尽快修复。

先打开着，等问题解决了再关

**Comment by wherewhere** [comment]
新的更新发布了，试一下

**Comment by Qing-JiuJiu** [comment]
> 新的更新发布了，试一下

可以了，会提示使用NET6.0环境，安装完后已能够正常使用，谢谢。

**Comment by wherewhere** [comment]
> > 新的更新发布了，试一下
> 
> 可以了，会提示使用NET6.0环境，安装完后已能够正常使用，谢谢。

坏WAS，就是不好用
