### ISSUE TITLE
无法连接到子系统

### ISSUE THREAD

**Issue by FreeDivers** [Paving-Base/APK-Installer#22]
我一打开adb就提示我连接WSA，然后我按照它的步骤来，但是仍然提示连接WSA

**Comment by wherewhere** [comment]
> ![image](https://user-images.githubusercontent.com/53342498/138683040-d5a51bff-1654-456a-adc4-f7b7ffd7e663.png)
> 又好了😂感觉有点玄学

好像发现问题了，是adb被占用了，还不会解决。。。
