### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by yejinson** [Paving-Base/APK-Installer#247]
### Describe the bug

安装报错
<a href="https://sm.ms/image/zx6iuGlsnBPRhVv" target="_blank"><img src="https://s2.loli.net/2022/09/26/zx6iuGlsnBPRhVv.png" ></a>

### Steps to reproduce the bug

双击安装

### App version

0.1.18

### Windows version

Windows 11 version 22H2 (25169)

### Android device

Windows Subsystem for Android™

**Comment by wherewhere** [comment]
。。。

**Comment by yejinson** [comment]
> 。。。

请问下软件正常情况下能在资源管理器里显示apk图标吗？我这在软件选取里面可以看到，但资源管理器里不行，不知道是软件还没实现这个功能还是跟什么软件冲突了？

**Comment by wherewhere** [comment]
没这功能，懒得写<img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />

**Comment by yejinson** [comment]
> 没这功能，懒得写<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">

好吧，那太遗憾了。
