### ISSUE TITLE
You should upload it to the store!

### ISSUE THREAD

**Issue by Diegorro98** [Paving-Base/APK-Installer#29]
I think that someone has copied your work (and made it worse) and uploaded it to the Microsoft Store ([link](https://www.microsoft.com/store/productId/9N4P75DXL6FG))
You should definitely upload it to the store, is a great job!

**Comment by wherewhere** [comment]
![Screenshot_20211210-123500.jpg](https://user-images.githubusercontent.com/27689196/145518140-135a3ed9-61f2-4670-96d0-91485a9541dd.jpg)

**Comment by wherewhere** [comment]
Published
https://www.microsoft.com/store/apps/9P2JFQ43FPPG
