### ISSUE TITLE
English translation not right

### ISSUE THREAD

**Issue by toineenzo** [Paving-Base/APK-Installer#291]
### Describe the bug

I submitted some translation improvements on Crowdin for the english strings as some of them are not gramatically correct. Please also note that the app name in the title bar is still in Chinese in the english version.

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/4921397/209873701-31b1773f-1f06-49dc-9dc5-eab80dbf1795.png)

### App version

0.1.20

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### Android device

Windows Subsystem for Android™

**Comment by wherewhere** [comment]
Updated
https://github.com/Paving-Base/APK-Installer/releases/tag/v0.1.22
