### ISSUE TITLE
[Bug] apk文件包含特殊符号时无法安装。

### ISSUE THREAD

**Issue by char-46** [Paving-Base/APK-Installer#298]
### Describe the bug

'[www.ghxi.com]Xposed edge pro_v8.0.1'

### Steps to reproduce the bug

目前可以确认`[`、`]`会引发异常。

### App version

0.1.20

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### Android device

Nomal Device

**Comment by wherewhere** [comment]
太怪了，我也不知道怎么解决这个问题。。。

**Comment by wherewhere** [comment]
你进入设置，把安装进度条关掉再试试

**Comment by char-46** [comment]
ok 了。
![image](https://user-images.githubusercontent.com/53117560/221573678-8f27f930-8be3-4eba-993c-55353790ab1f.png)

**Comment by char-46** [comment]
重新打开进度条就不行了。

**Comment by wherewhere** [comment]
我知道是怎么回事了，命令中不能出现这些字符，否则命令就错了，所以只能安装之前改名字了(我总不能把你的文件给改了吧。。。

**Comment by wherewhere** [comment]
等我解决吧(最近不想发布新版本，有个人一直在咕翻译，我要等他咕完了才能发布新版本

**Comment by char-46** [comment]
具体是哪里的翻译？我看看我能不能帮上？

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："where&nbsp;where ***@***.***&gt;;
发送时间：2023年2月27日(星期一) 晚上10:20
收件人："Paving-Base/APK-Installer" ***@***.***&gt;;
抄送："char46 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [Paving-Base/APK-Installer] [Bug] apk文件包含特殊符号时无法安装。 (Issue #298)
-----------------------------------

 

 
等我解决吧(最近不想发布新版本，有个人一直在咕翻译，我要等他咕完了才能发布新版本

**Comment by wherewhere** [comment]
中亚那边的语言

**Comment by wherewhere** [comment]
中亚那边的语言更新发布了，你看看
