### ISSUE TITLE
增加对于.apk.1文件的关联。

### ISSUE THREAD

**Issue by char-46** [Paving-Base/APK-Installer#334]
### Describe your feature request

通过 QQ 发送的文件都会被重命名，而现在及时使用 apk installer 打开 .apk.1 文件也会说文件类型错误。

### How important is this to you?

Important

### Describe the solution you'd like

是否可以关联到.apk.1文件。
或使用 apk installer 打开 .apk.1 文件时正常解析安装包。

**Comment by wherewhere** [comment]
.apk.1实际上后缀名是.1，我不可能给.1加的，你直接把文件拖拽到窗口上面就行了

**Comment by char-46** [comment]
有个问题是我手动关联之后打开.1文件会出问题……
![Clip_023610](https://github.com/Paving-Base/APK-Installer/assets/53117560/90134245-cd51-4f5a-8e1c-f85865e44c25)

或者哪怕我从命令行启动也会出问题，是不是可以先解析软件包再来说他是不是有效？

```
"C:\Program Files\WindowsApps\18184wherewhere.AndroidAppInstaller_0.1.25.0_x64__4v4sx105x6y4r\APKInstaller.exe" "%1"
```

**Comment by wherewhere** [comment]
因为你启动的方法是错误的，暂时不支持命令行启动。。。

**Comment by wherewhere** [comment]
。。。

**Comment by wherewhere** [comment]
已支持命令行打开 https://github.com/Paving-Base/APK-Installer-UWP/commit/166e5d3908553bd2f0a50fccdd9cf49682126a13
