### ISSUE TITLE
建议保存launch when ready设置

### ISSUE THREAD

**Issue by jwy090815** [Paving-Base/APK-Installer#35]
把launch when ready的勾去掉时下次启动时会自动勾上，有些人不需要launch when ready，需要保存打不打勾的状态，不然每次都要去掉勾

**Comment by wherewhere** [comment]
因为官方启动器就是这样的。。。
(下次加上

**Comment by oxygen-dioxide** [comment]
> 把launch when ready的勾去掉时下次启动时会自动勾上，有些人不需要launch when ready，需要保存打不打勾的状态，不然每次都要去掉勾

附议，win10官方appx安装器不保存launch when ready设置这个设计我并不喜欢，而且还希望能够细化选项（安装成功后，启动app/不启动app/不启动app并退出apk installer）

**Comment by wherewhere** [comment]
> > 把launch when ready的勾去掉时下次启动时会自动勾上，有些人不需要launch when ready，需要保存打不打勾的状态，不然每次都要去掉勾
> 
> 附议，win10官方appx安装器不保存launch when ready设置这个设计我并不喜欢，而且还希望能够细化选项（安装成功后，打开app/不打开app/不打开app并退出apk installer）

哼，我才不干呢，而且我也监控不了有没有启动成功<img alt="幽灵" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />
