### ISSUE TITLE
系统开机时第一次打开apk installer必定会闪退

### ISSUE THREAD

**Issue by jwy090815** [Paving-Base/APK-Installer#36]
已更新0.0.2版本，已经确保WSA系统启动完成，然后开机后第一次打开软件在Start ADB Server转圈转几次就开始卡住并闪退，之后打开就不会有闪退现象。

**Comment by wherewhere** [comment]
这个应该是adb的问题。。。

**Comment by bigsaltyfishes** [comment]
这个我测试了下，如果在运行的时候有非程序下载的adb在运行，就会引起崩溃，任务管理器里会看到原有adb进程被杀掉并启动了新的进程，然后进程会随程序一起退出

**Comment by bigsaltyfishes** [comment]
这个应该是Adb库有关

**Comment by bigsaltyfishes** [comment]
因为没办法直接Debug运行，我也不清楚究竟哪里出了问题

**Comment by wherewhere** [comment]
> 这个我测试了下，如果在运行的时候有非程序下载的adb在运行，就会引起崩溃，任务管理器里会看到原有adb进程被杀掉并启动了新的进程，然后进程会随程序一起退出

你就直接参与项目吧，一个一个push看着就累<img alt="幽灵" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />

**Comment by wherewhere** [comment]
> 这个我测试了下，如果在运行的时候有非程序下载的adb在运行，就会引起崩溃，任务管理器里会看到原有adb进程被杀掉并启动了新的进程，然后进程会随程序一起退出

之前有一种情况，就是wsa启动了但是没有启动，这时打开安装器就会崩掉，因为我当时没有写异步报错处理，所以一旦报错了就直接崩了。。。

**Comment by wherewhere** [comment]
> 因为没办法直接Debug运行，我也不清楚究竟哪里出了问题

话说有什么简单好用的log轮子吗？我以前用的是MetroLog，但是WAS用不了，然后就没得log记录用了。。。

**Comment by bigsaltyfishes** [comment]
> > 这个我测试了下，如果在运行的时候有非程序下载的adb在运行，就会引起崩溃，任务管理器里会看到原有adb进程被杀掉并启动了新的进程，然后进程会随程序一起退出
> 
> 之前有一种情况，就是wsa启动了但是没有启动，这时打开安装器就会崩掉，因为我当时没有写异步报错处理，所以一旦报错了就直接崩了。。。
![微信图片_20211103193109](https://user-images.githubusercontent.com/15278036/140098889-087d12c4-40f8-495e-be22-56605012c6c3.png)
我也不是很会调试这玩意儿，只能提供这么多信息了，不会汇编，看不出哪里有问题

**Comment by wherewhere** [comment]
> > > 这个我测试了下，如果在运行的时候有非程序下载的adb在运行，就会引起崩溃，任务管理器里会看到原有adb进程被杀掉并启动了新的进程，然后进程会随程序一起退出
> > 
> > 之前有一种情况，就是wsa启动了但是没有启动，这时打开安装器就会崩掉，因为我当时没有写异步报错处理，所以一旦报错了就直接崩了。。。
> 
> ![微信图片_20211103193109](https://user-images.githubusercontent.com/15278036/140098889-087d12c4-40f8-495e-be22-56605012c6c3.png)
> 我也不是很会调试这玩意儿，只能提供这么多信息了，不会汇编，看不出哪里有问题
> 
> 

这玩意我也不会。。。
或许可以检测过早关闭再给它打开。。。

**Comment by sadtango289** [comment]
> 这个应该是adb的问题。。。

if you not mind please make a video about how to install and test an android app on win 10

**Comment by wherewhere** [comment]
> > 这个应该是adb的问题。。。
> 
> if you not mind please make a video about how to install and test an android app on win 10

No Win10. Only 11.
