### ISSUE TITLE
无法保存窗口大小和窗口位置

### ISSUE THREAD

**Issue by jwy090815** [Paving-Base/APK-Installer#37]
每次打开都会重置

**Comment by wherewhere** [comment]
因为WinUI3没有现代的窗口管理API，所以改窗口大小必须用古老的Win32，于是每次启动都会修改一次大小。。。
如果有需求的话我会在设置里加开关

**Comment by EP012014** [comment]
> 因为WinUI3没有现代的窗口管理API

试一下PreferredLaunchSize？

**Comment by wherewhere** [comment]
> > 因为WinUI3没有现代的窗口管理API
> 
> 试一下PreferredLaunchSize？

这是Win32，不是UWP。。。

**Comment by EP012014** [comment]
> > > 因为WinUI3没有现代的窗口管理API
> > 
> > 
> > 试一下PreferredLaunchSize？
> 
> 这是WPF，不是UWP。。。

Windows App SDK不是WPF吧。
不是把UWP的各个模块（UWP XAML；WinRT API；应用容器；应用生命周期）解耦然后拼起来给传统桌面应用用吗？
这个应该在WinUI3里面存在吧

**Comment by wherewhere** [comment]
> > > > 因为WinUI3没有现代的窗口管理API
> > > 
> > > 
> > > 试一下PreferredLaunchSize？
> > 
> > 这是WPF，不是UWP。。。
> 
> Windows App SDK不是WPF吧。
> 不是把UWP的各个模块（UWP XAML；WinRT API；应用容器；应用生命周期）解耦然后拼起来给传统桌面应用用吗？
> 这个应该在WinUI3里面存在吧

本质就是WPF，不能完全当UWP看待，而且现在还是半成品，很多接口还没有，不然谁会去用那么古老的方法(甚至有些旧的删了新的还没加，然后就很烦。。。

**Comment by EP012014** [comment]
> 本质就是WPF

啊，这。

**Comment by ikas-mc** [comment]
使用[AppWindow](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow) 吧
目前uwp与windows app sdk 最新的窗口管理类 :AppWindow

**Comment by wherewhere** [comment]
> 使用[AppWindow](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow) 吧
> 目前uwp与windows app sdk 最新的窗口管理类 :AppWindow
> 

已经用了，不过很难用，而且本质还是原来的方法，没有变成UWP的现代化窗口。。。

**Comment by wherewhere** [comment]
> uwp的applicationview限制与问题更多了...
> 我正想试试AppWindow

可能我对WPF印象不太好，AppWindow就是Window，而且目前啥都不支持，一点也不好玩。。。
(UWP有AppWindow了吗？

**Comment by wherewhere** [comment]
> 有了...
> https://docs.microsoft.com/zh-cn/windows/apps/design/layout/app-window
> 相比于win32的原生window,AppWindow已经可以了

原来WinUI的那些毛病就是AppWindow搞出来的。。。

**Comment by ikas-mc** [comment]
与win32的通信我试过几个方案了..最终还是放弃了..
我建议你可以参考Files的pipe,使用pipe更方便一点

我自己的方案最终仅保留2个必须要调用win32的方法...直接调用就完事了,那个本地回环你也直接调用那个命令加个白名单完事了...

主要是uwp不值得继续投资了..哈哈

**Comment by wherewhere** [comment]
> 与win32的通信我试过几个方案了..最终还是放弃了..
> 我建议你可以参考Files的pipe,使用pipe更方便一点
> https://github.com/files-community/Files/blob/main/src/Files.Launcher/Program.cs
> 
> 我自己的方案最终仅保留2个必须要调用win32的方法...直接调用就完事了,那个本地回环你也直接调用那个命令加个白名单完事了...
> 
> 主要是uwp不值得继续投资了..(微软自己都放弃了..真的..太累了)
> 我看你又搞了一个uwp的..没必要啊,还是继续用winui3啊
> 
> 
> https://github.com/microsoft/WindowsAppSDK/discussions/1055
> https://github.com/microsoft/WindowsAppSDK/discussions/1071
> uwp不再有安全保证,也没有新的技术投入....🤣

真糟糕，我好不容易迁移到应用间通信，现在你又给我搞了个更好用的🤣🤣🤣
