### ISSUE TITLE
Can't install any APKs

### ISSUE THREAD

**Issue by Sayor0630** [Paving-Base/APK-Installer#38]
I can't install any APKs. Just saying Waiting for Device. Install button Blacked out. WSA is up and running. ADB is installed correctly.
![image](https://user-images.githubusercontent.com/77576588/139523451-fcfc5666-4aa9-4add-ab29-82ea2eef708c.png)

**Comment by wherewhere** [comment]
Tab to settings, then choose device manualy.

**Comment by Sayor0630** [comment]
> Tab to settings, then choose device manually.

Where s the settings? How can I choose device?

**Comment by wherewhere** [comment]
> > Tab to settings, then choose device manually.
> 
> Where s the settings? How can I choose device?

Try Tab<img alt="流汗滑稽" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />

**Comment by Sayor0630** [comment]
> > > Tab to settings, then choose device manually.
> > 
> > 
> > Where s the settings? How can I choose device?
> 
> Try Tab<img alt="流汗滑稽" width="20px" src="https://camo.githubusercontent.com/012ea43d58582210641ce32e68b3368526ee33e6ff3447fc67a19ec3219e6e27/68747470733a2f2f7261772e666173746769742e6f72672f54616e67656e742d39302f436f6f6c61706b2d5557502f6d61737465722f436f6f6c61706b5557502f436f6f6c61706b5557502f4173736574732f456d6f6a692f313235392e706e67">

Are you bully me?🤔😑

**Comment by wherewhere** [comment]
> > > > Tab to settings, then choose device manually.
> > > 
> > > 
> > > Where s the settings? How can I choose device?
> > 
> > Try Tab<img alt="流汗滑稽" width="20px" src="https://camo.githubusercontent.com/012ea43d58582210641ce32e68b3368526ee33e6ff3447fc67a19ec3219e6e27/68747470733a2f2f7261772e666173746769742e6f72672f54616e67656e742d39302f436f6f6c61706b2d5557502f6d61737465722f436f6f6c61706b5557502f436f6f6c61706b5557502f4173736574732f456d6f6a692f313235392e706e67">
> 
> Are you bully me?🤔😑

![mmexport1634101833118~2.png](https://user-images.githubusercontent.com/27689196/139530665-83aa48c6-db5a-4e72-add0-c2d8d5cbde56.png)

**Comment by Sayor0630** [comment]
Nothing
![image](https://user-images.githubusercontent.com/77576588/139530789-6062c076-b2e0-4ec6-80de-1a47635621ed.png)

**Comment by wherewhere** [comment]
> Nothing
> ![image](https://user-images.githubusercontent.com/77576588/139530789-6062c076-b2e0-4ec6-80de-1a47635621ed.png)
> 

Have you open Developer mode?

**Comment by Sayor0630** [comment]
> > Nothing
> > ![image](https://user-images.githubusercontent.com/77576588/139530789-6062c076-b2e0-4ec6-80de-1a47635621ed.png)
> 
> Have you open Developer mode?

yes.

**Comment by wherewhere** [comment]
> > > Nothing
> > > ![image](https://user-images.githubusercontent.com/77576588/139530789-6062c076-b2e0-4ec6-80de-1a47635621ed.png)
> > 
> > Have you open Developer mode?
> 
> yes.

Like this?
 ![​开发人员模式​](https://raw.githubusercontent.com/Paving-Base/APK-Installer/screenshots/Helpers/How%20To%20Connect%20WSA/Snipaste_2021-10-22_14-57-56.png)

**Comment by Sayor0630** [comment]
> > > > Nothing
> > > > ![image](https://user-images.githubusercontent.com/77576588/139530789-6062c076-b2e0-4ec6-80de-1a47635621ed.png)
> > > 
> > > 
> > > Have you open Developer mode?
> > 
> > 
> > yes.
> 
> Like this?  ![​开发人员模式​](https://raw.githubusercontent.com/Paving-Base/APK-Installer/screenshots/Helpers/How%20To%20Connect%20WSA/Snipaste_2021-10-22_14-57-56.png)

Yes
![image](https://user-images.githubusercontent.com/77576588/139531325-6f7ca57f-9059-4e7c-a037-e2c696e98fdd.png)

**Comment by wherewhere** [comment]
> > > > > Nothing
> > > > > ![image](https://user-images.githubusercontent.com/77576588/139530789-6062c076-b2e0-4ec6-80de-1a47635621ed.png)
> > > > 
> > > > 
> > > > Have you open Developer mode?
> > > 
> > > 
> > > yes.
> > 
> > Like this?  ![​开发人员模式​](https://raw.githubusercontent.com/Paving-Base/APK-Installer/screenshots/Helpers/How%20To%20Connect%20WSA/Snipaste_2021-10-22_14-57-56.png)
> 
> Yes
> ![image](https://user-images.githubusercontent.com/77576588/139531325-6f7ca57f-9059-4e7c-a037-e2c696e98fdd.png)
> 

I don't know...

**Comment by bharat787878** [comment]
Same problem here, how to fix it?
