### ISSUE TITLE
请求更换压缩格式

### ISSUE THREAD

**Issue by yyzzi** [Paving-Base/APK-Installer#39]
如题,由于RAR格式的特殊性,会给一些设备解压带来不小的麻烦

**Comment by wherewhere** [comment]
不会更换，除非你什么解压软件都没装，否则都能解压

**Comment by yyzzi** [comment]
> 不会更换，除非你什么解压软件都没装，否则都能解压

我的错，7z只是不能压缩rar。想当然觉得也无法解压了
