### ISSUE TITLE
安装软件时请求进度条可视化

### ISSUE THREAD

**Issue by wangxu-610-zz** [Paving-Base/APK-Installer#40]
![image](https://user-images.githubusercontent.com/57589459/139525486-6165feb8-f37c-405e-9004-6f56394aa923.png)
像这种的大型软件安装的时候不知道安装了多久

**Comment by wangxu-610** [comment]
来一个像WSA里面安装软件那样，有一个进度条来显示目前安装软件的进度

**Comment by wherewhere** [comment]
暂时无法实现，如果你可以提供可用的解决方案，我会添加的

**Comment by oxygen-dioxide** [comment]
> 来一个像WSA里面安装软件那样，有一个进度条来显示目前安装软件的进度

安卓貌似做不到，安卓手机里面装apk也没有进度条的

**Comment by IamChocolate** [comment]
> > 来一个像WSA里面安装软件那样，有一个进度条来显示目前安装软件的进度
> 
> 安卓貌似做不到，安卓手机里面装apk也没有进度条的

原生apk安装器明明有一个不准确的进度条。。。

**Comment by wherewhere** [comment]
> > > 来一个像WSA里面安装软件那样，有一个进度条来显示目前安装软件的进度
> > 
> > 安卓貌似做不到，安卓手机里面装apk也没有进度条的
> 
> 原生安装包管理器明明有一个不准确的进度条。。。

adb没有
