### ISSUE TITLE
带有GAPPS和magisk的WSA无法连接

### ISSUE THREAD

**Issue by Zaphkito** [Paving-Base/APK-Installer#42]
直接cmd用adb可以检测到，但是APK-Installer和隔壁的WSAtoolbox都检测不到
希望这边能解决一下
似乎是安装了带有GAPPS和magisk的那个WSA会出现这个情况
![`N8SNV(RC4%D2T30M8}4QZ9](https://user-images.githubusercontent.com/64299266/139577646-65119eab-b7fb-4ff7-b70b-d4a26ee3ddd4.png)

**Comment by wherewhere** [comment]
新版本应该能检测到了，或者是你新建的adb占用了安装器的，导致谁也连不上。。。

**Comment by Zaphkito** [comment]
虽然但是，我将电脑重启后再安装也无法检测到，只能手动用cmd连

**Comment by wherewhere** [comment]
> 虽然但是，我将电脑重启后再安装也无法检测到，只能手动用cmd连
> 你要不发一个带debug的，我运行后先看一眼日志

这个Debug不出来，我也不知道是怎么回事。。。

**Comment by bigsaltyfishes** [comment]
先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果

**Comment by Zaphkito** [comment]
> 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果

![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)

**Comment by bigsaltyfishes** [comment]
> > 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果
> 
> ![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)

这个跟子系统有关的标记都被删掉了，目前也没有别的检测方法

**Comment by bigsaltyfishes** [comment]
> > > 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)
> 
> 这个跟子系统有关的标记都被删掉了，目前也没有别的检测方法

你可以手动修改prop值让程序能正常识别

**Comment by Zaphkito** [comment]
> > > > 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)
> > 
> > 
> > 这个跟子系统有关的标记都被删掉了，目前也没有别的检测方法
> 
> 你可以手动修改prop值让程序能正常识别

具体怎么修改细说

**Comment by bigsaltyfishes** [comment]
> > > > > 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)
> > > 
> > > 
> > > 这个跟子系统有关的标记都被删掉了，目前也没有别的检测方法
> > 
> > 
> > 你可以手动修改prop值让程序能正常识别
> 
> 具体怎么修改细说

adb shell里运行命令setprop ro.product.odm.brand Windows ，然后再运行getprop|grep Windows 看看有没有返回值（可能需要root权限）

**Comment by Zaphkito** [comment]
![image](https://user-images.githubusercontent.com/64299266/139785285-4cf1a500-e2a8-4a2f-9bd3-472ad4abd445.png)
emm有什么奇奇怪怪的错误

**Comment by Zaphkito** [comment]
> > > > > > 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)
> > > > 
> > > > 
> > > > 这个跟子系统有关的标记都被删掉了，目前也没有别的检测方法
> > > 
> > > 
> > > 你可以手动修改prop值让程序能正常识别
> > 
> > 
> > 具体怎么修改细说
> 
> adb shell里运行命令setprop ro.product.odm.brand Windows ，然后再运行getprop|grep Windows 看看有没有返回值（可能需要root权限）

![image](https://user-images.githubusercontent.com/64299266/139785721-b2dd918b-767b-46f5-b4a2-e22aa0a444d0.png)
zhe'hao'x这好像有什么奇奇怪怪的错误

**Comment by Zaphkito** [comment]
> > > > > > > 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)
> > > > > 
> > > > > 
> > > > > 这个跟子系统有关的标记都被删掉了，目前也没有别的检测方法
> > > > 
> > > > 
> > > > 你可以手动修改prop值让程序能正常识别
> > > 
> > > 
> > > 具体怎么修改细说
> > 
> > 
> > adb shell里运行命令setprop ro.product.odm.brand Windows ，然后再运行getprop|grep Windows 看看有没有返回值（可能需要root权限）
> 
> ![image](https://user-images.githubusercontent.com/64299266/139785721-b2dd918b-767b-46f5-b4a2-e22aa0a444d0.png) 这好像有什么奇奇怪怪的错误

![image](https://user-images.githubusercontent.com/64299266/139786641-0f301f74-35ac-4e50-859e-7b30fe4cdcbf.png)
我估计错误应该是因为system分区还锁着，另外我还发现这个props被MagiskOnWSA那个作者改成Google了，现在设备的环境完全是Google Pixel 5

**Comment by bigsaltyfishes** [comment]
> > > > > > > > 先运行一下adb shell，看看能否正常连接，如果能正常进入命令行，再执行下 getprop|grep Windows 和 getprop|grep Subsystem ，看看有没有返回结果
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://user-images.githubusercontent.com/64299266/139784106-44f5e8c5-e9f7-4651-aaf4-da6685cb3ca6.png)
> > > > > > 
> > > > > > 
> > > > > > 这个跟子系统有关的标记都被删掉了，目前也没有别的检测方法
> > > > > 
> > > > > 
> > > > > 你可以手动修改prop值让程序能正常识别
> > > > 
> > > > 
> > > > 具体怎么修改细说
> > > 
> > > 
> > > adb shell里运行命令setprop ro.product.odm.brand Windows ，然后再运行getprop|grep Windows 看看有没有返回值（可能需要root权限）
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/64299266/139785721-b2dd918b-767b-46f5-b4a2-e22aa0a444d0.png) 这好像有什么奇奇怪怪的错误
> 
> ![image](https://user-images.githubusercontent.com/64299266/139786641-0f301f74-35ac-4e50-859e-7b30fe4cdcbf.png) 我估计错误应该是因为system分区还锁着，另外我还发现这个props被MagiskOnWSA那个作者改成Google了，现在设备的环境完全是Google Pixel 5

这个就没办法了，原来的那个gapps脚本留下了odm prop没改所以可以识别到，MagiskOnWSA全给整掉了，晚点我看看能不能弄个magisk模块看看能不能改掉odm prop

**Comment by bigsaltyfishes** [comment]
如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照

**Comment by Zaphkito** [comment]
> 如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照

![image](https://user-images.githubusercontent.com/64299266/139789392-e50f6cfe-b898-4a08-b058-63ac6ee9caea.png)
返回的结果如下
[init.svc.windows-camera-hal]: [running]
[init.svc.windows-composer-hal]: [running]
[init.svc.windows-gnss-hal]: [running]
[init.svc.windows-logcat]: [running]
[init.svc.windows-power-hal]: [running]
[ro.board.platform]: [windows]
[ro.boot.hardware]: [windows_x86_64]
[ro.hardware]: [windows_x86_64]
[ro.hardware.audio.primary]: [windows]
[ro.product.board]: [windows]

**Comment by bigsaltyfishes** [comment]
> > 如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照
> 
> ![image](https://user-images.githubusercontent.com/64299266/139789392-e50f6cfe-b898-4a08-b058-63ac6ee9caea.png) 返回的结果如下 [init.svc.windows-camera-hal]: [running] [init.svc.windows-composer-hal]: [running] [init.svc.windows-gnss-hal]: [running] [init.svc.windows-logcat]: [running] [init.svc.windows-power-hal]: [running] [ro.board.platform]: [windows] [ro.boot.hardware]: [windows_x86_64] [ro.hardware]: [windows_x86_64] [ro.hardware.audio.primary]: [windows] [ro.product.board]: [windows]

已经做出更改，安装这个试试（有效期7天）：
[](https://cloud.189.cn/t/JnEFjeE3eaqe) (访问码:08bj)

**Comment by Zaphkito** [comment]
> > > 如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/64299266/139789392-e50f6cfe-b898-4a08-b058-63ac6ee9caea.png) 返回的结果如下 [init.svc.windows-camera-hal]: [running] [init.svc.windows-composer-hal]: [running] [init.svc.windows-gnss-hal]: [running] [init.svc.windows-logcat]: [running] [init.svc.windows-power-hal]: [running] [ro.board.platform]: [windows] [ro.boot.hardware]: [windows_x86_64] [ro.hardware]: [windows_x86_64] [ro.hardware.audio.primary]: [windows] [ro.product.board]: [windows]
> 
> 已经做出更改，安装这个试试（有效期7天）： [https://cloud.189.cn/t/JnEFjeE3eaqe (访问码:08bj)](url) (访问码:08bj)

![image](https://user-images.githubusercontent.com/64299266/139803296-3b8f06fb-6771-4283-8562-fdbb7add1f1e.png)
无法正常下载和安装ADB组件

**Comment by bigsaltyfishes** [comment]
> > > > 如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/64299266/139789392-e50f6cfe-b898-4a08-b058-63ac6ee9caea.png) 返回的结果如下 [init.svc.windows-camera-hal]: [running] [init.svc.windows-composer-hal]: [running] [init.svc.windows-gnss-hal]: [running] [init.svc.windows-logcat]: [running] [init.svc.windows-power-hal]: [running] [ro.board.platform]: [windows] [ro.boot.hardware]: [windows_x86_64] [ro.hardware]: [windows_x86_64] [ro.hardware.audio.primary]: [windows] [ro.product.board]: [windows]
> > 
> > 
> > 已经做出更改，安装这个试试（有效期7天）： [https://cloud.189.cn/t/JnEFjeE3eaqe (访问码:08bj)](url) (访问码:08bj)
> 
> ![image](https://user-images.githubusercontent.com/64299266/139803296-3b8f06fb-6771-4283-8562-fdbb7add1f1e.png) 无法正常下载和安装ADB组件
这个可能和网络有关，也可能是因为你安装着原来的版本

**Comment by bigsaltyfishes** [comment]
试一下添加hosts
120.253.255.34 dl.google.com

**Comment by Zaphkito** [comment]
> 试一下添加hosts 120.253.255.34 dl.google.com

![image](https://user-images.githubusercontent.com/64299266/139805617-50914f31-8c4c-4892-acec-1640650cb0a1.png)
![image](https://user-images.githubusercontent.com/64299266/139805638-9f269496-cc8b-4ac9-8995-64d5888ce9dd.png)
可以正常安装了

**Comment by wherewhere** [comment]
> > > > 如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/64299266/139789392-e50f6cfe-b898-4a08-b058-63ac6ee9caea.png) 返回的结果如下 [init.svc.windows-camera-hal]: [running] [init.svc.windows-composer-hal]: [running] [init.svc.windows-gnss-hal]: [running] [init.svc.windows-logcat]: [running] [init.svc.windows-power-hal]: [running] [ro.board.platform]: [windows] [ro.boot.hardware]: [windows_x86_64] [ro.hardware]: [windows_x86_64] [ro.hardware.audio.primary]: [windows] [ro.product.board]: [windows]
> > 
> > 已经做出更改，安装这个试试（有效期7天）： [https://cloud.189.cn/t/JnEFjeE3eaqe (访问码:08bj)](url) (访问码:08bj)
> 
> ![image](https://user-images.githubusercontent.com/64299266/139803296-3b8f06fb-6771-4283-8562-fdbb7add1f1e.png)
> 无法正常下载和安装ADB组件

我用的是国内的源，怎么会连不上呢？

**Comment by Zaphkito** [comment]
> > > > > 如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/64299266/139789392-e50f6cfe-b898-4a08-b058-63ac6ee9caea.png) 返回的结果如下 [init.svc.windows-camera-hal]: [running] [init.svc.windows-composer-hal]: [running] [init.svc.windows-gnss-hal]: [running] [init.svc.windows-logcat]: [running] [init.svc.windows-power-hal]: [running] [ro.board.platform]: [windows] [ro.boot.hardware]: [windows_x86_64] [ro.hardware]: [windows_x86_64] [ro.hardware.audio.primary]: [windows] [ro.product.board]: [windows]
> > > 
> > > 
> > > 已经做出更改，安装这个试试（有效期7天）： [https://cloud.189.cn/t/JnEFjeE3eaqe (访问码:08bj)](url) (访问码:08bj)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/64299266/139803296-3b8f06fb-6771-4283-8562-fdbb7add1f1e.png)
> > 无法正常下载和安装ADB组件
> 
> 我用的是国内的源，怎么会连不上呢？

管他呢反正后来能下载安装了，然后装了那个人的版本可以安装apk了（

**Comment by bigsaltyfishes** [comment]
> > > > > 如果可以的话，麻烦执行下getprop|grep windows ，我注意到微软在里面还加了些别的东西，也许可以作为识别wsa的prop，这里需要些数据和原始wsa对照
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/64299266/139789392-e50f6cfe-b898-4a08-b058-63ac6ee9caea.png) 返回的结果如下 [init.svc.windows-camera-hal]: [running] [init.svc.windows-composer-hal]: [running] [init.svc.windows-gnss-hal]: [running] [init.svc.windows-logcat]: [running] [init.svc.windows-power-hal]: [running] [ro.board.platform]: [windows] [ro.boot.hardware]: [windows_x86_64] [ro.hardware]: [windows_x86_64] [ro.hardware.audio.primary]: [windows] [ro.product.board]: [windows]
> > > 
> > > 
> > > 已经做出更改，安装这个试试（有效期7天）： [https://cloud.189.cn/t/JnEFjeE3eaqe (访问码:08bj)](url) (访问码:08bj)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/64299266/139803296-3b8f06fb-6771-4283-8562-fdbb7add1f1e.png)
> > 无法正常下载和安装ADB组件
> 
> 我用的是国内的源，怎么会连不上呢？

我是因为校园网dns污染一直连不上，要加个hosts
