### ISSUE TITLE
希望把应用安装器在开始菜单中的显示隐藏

### ISSUE THREAD

**Issue by Gaoyifei1011** [Paving-Base/APK-Installer#49]
目前看来这个应用也是辅助wsa的应用安装的，希望在开始菜单中将APP入口隐藏，仅通过关联文件实现（applistentry=none）

**Comment by wherewhere** [comment]
防止有小白看不见生气<img alt="流汗滑稽" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />

**Comment by Gaoyifei1011** [comment]
原来如此，好吧，那能否在未来的版本中优化一下开始菜单打开应用后的操作方式呢，选择电脑上的apk文件安装呢

**Comment by wherewhere** [comment]
> 原来如此，好吧，那能否在未来的版本中优化一下开始菜单打开应用后的操作方式呢，选择电脑上的apk文件安装呢

本来是要加拖入选中的，但是不知道什么回事造不出来。。。

**Comment by Gaoyifei1011** [comment]
哎呀，好吧，不过我觉得目前能否实现一下打开应用后选择本地的apk安装，而不是打开应用后显示这个内容
![ba648681-8ebb-40ed-9226-75eb40b79dd6 1](https://user-images.githubusercontent.com/49179966/140633038-77546e6d-4c18-4497-ad3e-0f0a746009a4.jpg)
![图片](https://user-images.githubusercontent.com/49179966/140633052-a6aea836-ab1b-411e-9d46-e59fefe28c55.png)

**Comment by wherewhere** [comment]
> 哎呀，好吧，不过我觉得目前能否实现一下打开应用后选择本地的apk安装，而不是打开应用后显示这个内容
> ![ba648681-8ebb-40ed-9226-75eb40b79dd6 1](https://user-images.githubusercontent.com/49179966/140633038-77546e6d-4c18-4497-ad3e-0f0a746009a4.jpg)
> ![图片](https://user-images.githubusercontent.com/49179966/140633052-a6aea836-ab1b-411e-9d46-e59fefe28c55.png)
> 

应该官方的App Installer就长这样啊

**Comment by Gaoyifei1011** [comment]
但是官方的APP installer是隐藏了开始菜单的入口的，所以就可以不用处理那一部分啊，但是你的应用是保留开始菜单的入口的，那是不是应该包含开始菜单入口的处理呢（一般应用安装器都是没有主程序入口的，包括Android的打包安装器）

**Comment by wherewhere** [comment]
> 但是官方的APP installer是隐藏了开始菜单的入口的，所以就可以不用处理那一部分啊，但是你的应用是保留开始菜单的入口的，那是不是应该包含开始菜单入口的处理呢（一般应用安装器都是没有主程序入口的，包括Android的打包安装器）

然而官方的早期也是没有隐藏入口的，我这个的提示都是直接抄官方的。。。

**Comment by wherewhere** [comment]
现在已经加入了选择。。。
