### ISSUE TITLE
可否添加多国语言以及BUG反馈

### ISSUE THREAD

**Issue by GoogleChinaCEO** [Paving-Base/APK-Installer#5]
单一的English看着总感觉不是很舒适（虽然自己能看得懂
还有就是在WSA已经安装该应用情况下在Windows双击已安装过的APK文件会导致闪退，未安装的APK则不会闪退
![image](https://user-images.githubusercontent.com/38829308/138556946-a6b87970-d325-4336-8899-9b4f18874f4f.png)

**Comment by wherewhere** [comment]
来翻译啊<img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" /><img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" /><img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />
https://crowdin.com/project/APKInstaller
