### ISSUE TITLE
证书失效？

### ISSUE THREAD

**Issue by Miho-an-kou** [Paving-Base/APK-Installer#52]
找到了捆绑: D:\CoolapkUWP_2.1.38.0_Test\CoolapkUWP_2.1.38.0_x86_x64_arm_arm64.appxbundle
找到证书: D:\CoolapkUWP_2.1.38.0_Test\CoolapkUWP_2.1.38.0_x86_x64_arm_arm64.cer
错误: 开发人员证书“D:\CoolapkUWP_2.1.38.0_Test\CoolapkUWP_2.1.38.0_x86_x64_arm_arm64.cer”已到期。一个可能的原因是系统 时钟未设置为正确的日期和时间。如果系统设置正确，请与应用程序所有者联系以使用有效的证书重新创建包或捆绑。

**Comment by wherewhere** [comment]
隔壁的事情别到这里问啊。。。
