### ISSUE TITLE
双击apk文件无法进入安装界面，一直在checking

### ISSUE THREAD

**Issue by EnderCell** [Paving-Base/APK-Installer#53]
安装子系统前双击apk文件会有提示要先安装子系统，但安装好后就进不去安装界面了，一直在checking转圈

**Comment by EnderCell** [comment]
![屏幕截图 2021-11-11 230803](https://user-images.githubusercontent.com/91339098/141321140-332649b9-a55f-49a3-8f9b-4fc5e08d964f.jpg)

**Comment by wherewhere** [comment]
你关掉再打开试试(也有可能是你的安装包是坏的
