### ISSUE TITLE
APK Installer v0.1.4 doesn't work

### ISSUE THREAD

**Issue by Void48** [Paving-Base/APK-Installer#67]
previous release works

**Comment by wherewhere** [comment]
???

**Comment by Void48** [comment]
> ???

it doesn't open. try for yourself lol

**Comment by wherewhere** [comment]
> > ???
> 
> it doesn't open. try for yourself lol

???
![mmexport1637245499866.png](https://user-images.githubusercontent.com/27689196/142744559-46447f9f-1525-407f-a7f0-79ec531f38d9.png)
![mmexport1637245503202.png](https://user-images.githubusercontent.com/27689196/142744564-06750e28-eb79-469f-9a1e-63ba0b7a85c0.png)

**Comment by wherewhere** [comment]
It will crash the first time you run it. Then open it again and it should work. This may be a problem of ADB...
