### ISSUE TITLE
Use the new App Installer UI instead of the old one

### ISSUE THREAD

**Issue by Void48** [Paving-Base/APK-Installer#7]
![image](https://user-images.githubusercontent.com/85196642/138557510-f61829a8-047c-44c1-bfa1-09a6c5c1ca1f.png)

**Comment by wherewhere** [comment]
Now it's coming.

**Comment by Void48** [comment]
still missing the bold text in new app installer

**Comment by Void48** [comment]
![image](https://user-images.githubusercontent.com/85196642/142727583-17956485-d71a-4fd8-96b0-0f4f4b5147a4.png)

**Comment by wherewhere** [comment]
> still missing the bold text in new app installer

I don't like that <img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />.

**Comment by Void48** [comment]
> > still missing the bold text in new app installer
> 
> I don't like that <img alt="Sweating funny" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png">.

What if it can be optional like a setting to turn it on?

**Comment by wherewhere** [comment]
> > > still missing the bold text in new app installer
> > 
> > I don't like that <img alt="Sweating funny" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png">.
> 
> What if it can be optional like a setting to turn it on?

NOP
