### ISSUE TITLE
[功能请求与问题] 安装完成后关闭自身窗口

### ISSUE THREAD

**Issue by IamChocolate** [Paving-Base/APK-Installer#72]
能否添加选项在安装完成后自动关闭窗口
以及安装完成后自动删除安装包源文件

**Comment by wherewhere** [comment]
看起来大家都想要这个功能，那我就加上吧<img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />

**Comment by IamChocolate** [comment]
> 看起来大家都想要这个功能，那我就加上吧<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">

我看到更新日志里写
>3. 重新设计了设置页面

设置入口在哪.....<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">

**Comment by wherewhere** [comment]
> > 看起来大家都想要这个功能，那我就加上吧<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">
> 
> 我看到更新日志里写
> >3. 重新设计了设置页面
> 
> 设置入口在哪.....<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">
> 

你试试在弹窗的时候回车<img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />

**Comment by IamChocolate** [comment]
> 



> > > 看起来大家都想要这个功能，那我就加上吧<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">
> > 
> > 
> > 我看到更新日志里写
> > > 3. 重新设计了设置页面
> > 
> > 
> > 设置入口在哪.....<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">
> 
> 你试试在弹窗的时候回车<img alt="流汗滑稽" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png">

太隐蔽了，建议写在README.md里<img alt="流汗滑稽" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png">

**Comment by wherewhere** [comment]
> > 
> 
> 
> 
> > > > 看起来大家都想要这个功能，那我就加上吧<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">
> > > 
> > > 
> > > 我看到更新日志里写
> > > > 3. 重新设计了设置页面
> > > 
> > > 
> > > 设置入口在哪.....<img alt="幽灵" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png">
> > 
> > 你试试在弹窗的时候回车<img alt="流汗滑稽" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png">
> 
> 太隐蔽了，建议写在README.md里<img alt="流汗滑稽" width="20px" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png">

NOP
