### ISSUE TITLE
Part of program not translated

### ISSUE THREAD

**Issue by TechStudent11** [Paving-Base/APK-Installer#80]
This dialog is not in English.

![image](https://user-images.githubusercontent.com/76978184/149787306-f1f338ec-c193-4a4c-9755-415f1dd7df70.png)

I don't understand it, but I assume it's telling to start WSA.

**Comment by wherewhere** [comment]
> This dialog is not in English.
> 
> ![image](https://user-images.githubusercontent.com/76978184/149787306-f1f338ec-c193-4a4c-9755-415f1dd7df70.png)
> 
> I don't understand it, but I assume it's telling to start WSA.

Because this text is put on GitHub. It can't be multi-language. . .

**Comment by TechStudent11** [comment]
> > This dialog is not in English.
> > ![image](https://user-images.githubusercontent.com/76978184/149787306-f1f338ec-c193-4a4c-9755-415f1dd7df70.png)
> > I don't understand it, but I assume it's telling to start WSA.
> 
> Because this text is put on GitHub. It can't be multi-language. . . And this is not mine. Mine is not yet on the store. Please ask the author of this version of the application.

I do not understand. Is this your app?

**Comment by wherewhere** [comment]
> > > This dialog is not in English.
> > > ![image](https://user-images.githubusercontent.com/76978184/149787306-f1f338ec-c193-4a4c-9755-415f1dd7df70.png)
> > > I don't understand it, but I assume it's telling to start WSA.
> > 
> > Because this text is put on GitHub. It can't be multi-language. . . And this is not mine. Mine is not yet on the store. Please ask the author of this version of the application.
> 
> I do not understand. Is this your app?

Yes. Or not. This is a fork one of mine. An unofficial distribution

**Comment by wherewhere** [comment]
#79

**Comment by TechStudent11** [comment]
> > > > This dialog is not in English.
> > > > ![image](https://user-images.githubusercontent.com/76978184/149787306-f1f338ec-c193-4a4c-9755-415f1dd7df70.png)
> > > > I don't understand it, but I assume it's telling to start WSA.
> > > 
> > > 
> > > Because this text is put on GitHub. It can't be multi-language. . . And this is not mine. Mine is not yet on the store. Please ask the author of this version of the application.
> > 
> > 
> > I do not understand. Is this your app?
> 
> Yes. Or not. This is a fork one of mine. An unofficial distribution

Ohhhhh okay. I got it. Thanks!
