### ISSUE TITLE
[bug]？？？

### ISSUE THREAD

**Issue by meiruitesi** [Paving-Base/APK-Installer#84]
![QQ截图20220201144014](https://user-images.githubusercontent.com/84609642/151923554-622a8d0d-c163-4b2b-870f-e9b67cd8a3de.png)

**Comment by wherewhere** [comment]
Bug，而且可能是WinUI的Bug，我没法解决的那种(我终于知道为什么有一堆崩溃了。。。

**Comment by wherewhere** [comment]
> ![QQ截图20220201144014](https://user-images.githubusercontent.com/84609642/151923554-622a8d0d-c163-4b2b-870f-e9b67cd8a3de.png)
> 

看起来是没有安装Windows App SDK，你是从应用商店下载的还是从GitHub下载的？

**Comment by meiruitesi** [comment]
我是从应用商店下载的。。。。

**Comment by wherewhere** [comment]
那就是SDK的Bug了，你试试下载GitHub里的x86版，有可能是打包方式不同导致的Bug

**Comment by wherewhere** [comment]
如果仍然无法修复那么就尝试手动安装一下过去版本的依赖

**Comment by meiruitesi** [comment]
![image](https://user-images.githubusercontent.com/84609642/151983413-cafde129-f3b4-4ce8-a6c3-3ca765db7710.png)

**Comment by meiruitesi** [comment]
重装了下系统，解决了。。。。。
