### ISSUE TITLE
已阻止程序包 Microsoft.WindowsAppRuntime.1.0_0.319.455.0_x64__8wekyb3d8bbwe 的部署

### ISSUE THREAD

**Issue by HumanMusicX** [Paving-Base/APK-Installer#87]
已阻止程序包 Microsoft.WindowsAppRuntime.1.0_0.319.455.0_x64__8wekyb3d8bbwe 的部署，因为提供的程序包具有与已安装的程序
包相同的标识，但内容不相同。请提高要安装的程序包的版本号，或者删除系统上的每个用户的旧程序包，然后再安装此程序包。

注意: 有关其他信息，请在事件日志中查找 [ActivityId] 7e4e5d5e-199e-0002-de81-507e9e19d801，或使用命令行 Get-AppPackageLo
g -ActivityID 7e4e5d5e-199e-0002-de81-507e9e19d801
![屏幕截图 2022-02-07 220437](https://user-images.githubusercontent.com/46023154/152807990-9e78eff6-42b6-4d38-a7ad-59a73e8d9837.png)

**Comment by wherewhere** [comment]
请通过应用商店安装更新

**Comment by HumanMusicX** [comment]
> 

原因是我之前重置系统了，原来WindowsApps文件夹里的文件还在，导致不能覆盖。
通过获取WindowsApps文件夹权限删掉原来的文件夹才好！

**Comment by wherewhere** [comment]
。。。
