### ISSUE TITLE
缺少对自定义adb服务端口的兼容

### ISSUE THREAD

**Issue by IamChocolate** [Paving-Base/APK-Installer#90]
- 由于NVIDIA SHIELD串流时会占用adb默认端口5037导致adb启动时卡住
- 故设置环境变量ANDROID_ADB_SERVER_PORT自定义端口号
- 结果发现只有APK Installer会在启动adb服务时闪退

**Comment by IamChocolate** [comment]
顺便一问 底下这一行这是什么
![屏幕截图 2022-02-09 144550](https://user-images.githubusercontent.com/94111173/153136680-7b8353f0-16dd-49f4-963b-f0e9a979afe3.png)

**Comment by wherewhere** [comment]
> 顺便一问 底下这一行这是什么
> ![屏幕截图 2022-02-09 144550](https://user-images.githubusercontent.com/94111173/153136680-7b8353f0-16dd-49f4-963b-f0e9a979afe3.png)

原来那个垃圾开始上广告了，我觉得我可以不用只是谴责了

**Comment by wherewhere** [comment]
> - 由于NVIDIA SHIELD串流时会占用adb默认端口5037导致adb启动时卡住
> - 故设置环境变量ANDROID_ADB_SERVER_PORT自定义端口号
> - 结果发现只有APK Installer会在启动adb服务时闪退

这是一个很严重的问题，感谢提出，不过如果不用WSA给的端口号也连不上WSA啊。。。

**Comment by IamChocolate** [comment]
> > 顺便一问 底下这一行这是什么
> > ![屏幕截图 2022-02-09 144550](https://user-images.githubusercontent.com/94111173/153136680-7b8353f0-16dd-49f4-963b-f0e9a979afe3.png)
> 
> 原来那个垃圾开始上广告了，我觉得我可以不用只是谴责了

可否展开讲讲？

**Comment by wherewhere** [comment]
> > > 顺便一问 底下这一行这是什么
> > > ![屏幕截图 2022-02-09 144550](https://user-images.githubusercontent.com/94111173/153136680-7b8353f0-16dd-49f4-963b-f0e9a979afe3.png)
> > 
> > 原来那个垃圾开始上广告了，我觉得我可以不用只是谴责了
> 
> 可否展开讲讲？

简单来说就是这位在我上架之前盗我代码上架，吸引完用户之后就露出真面目了。。。

**Comment by IamChocolate** [comment]
> > > > 顺便一问 底下这一行这是什么
> > > > ![屏幕截图 2022-02-09 144550](https://user-images.githubusercontent.com/94111173/153136680-7b8353f0-16dd-49f4-963b-f0e9a979afe3.png)
> > > 
> > > 
> > > 原来那个垃圾开始上广告了，我觉得我可以不用只是谴责了
> > 
> > 
> > 可否展开讲讲？
> 
> 简单来说就是这位在我上架之前盗我代码上架，吸引完用户之后就露出真面目了。。。

吓人 赶紧卸载了换了你的版本 现在自定义 ANDROID_ADB_SERVER_PORT 不会闪退了
话说既然已经开始加广告牟利了应该可以挂耻辱柱了吧

**Comment by IamChocolate** [comment]
> > > > 顺便一问 底下这一行这是什么
> > > > ![屏幕截图 2022-02-09 144550](https://user-images.githubusercontent.com/94111173/153136680-7b8353f0-16dd-49f4-963b-f0e9a979afe3.png)
> > > 
> > > 
> > > 原来那个垃圾开始上广告了，我觉得我可以不用只是谴责了
> > 
> > 
> > 可否展开讲讲？
> 
> 简单来说就是这位在我上架之前盗我代码上架，吸引完用户之后就露出真面目了。。。

吓人 卸载换你的版本了 但是仍然存在闪退问题 手动连接测试一切正常
![a](https://user-images.githubusercontent.com/94111173/153337498-53fe7103-406e-40f4-8252-8215eea81a7f.png)
