### ISSUE TITLE
无法下载，报错0x80072EFE

### ISSUE THREAD

**Issue by Macrohard-X** [Paving-Base/APK-Installer#97]
![image](https://user-images.githubusercontent.com/58348680/154676826-1c94b5ef-aaf1-4c49-9d35-13a18f574c63.png)

**Comment by Macrohard-X** [comment]
商店其它应用可以正常下载

**Comment by wherewhere** [comment]
> 商店其它应用可以正常下载

这个你应该找微软才对。。。
